### ISSUE TITLE
import ply file to unreal engine failed

### ISSUE THREAD

**Issue by yang1hu** [Vanessik/HAAR#1]
Hi! this is a great project ! i successfully get the results. however ,when i try to import the results into unreal engine.No response .could you tell me the method that you display the results

**Comment by Vanessik** [comment]
Hi @yang1hu ! Thanks for your feedback. For export into Unreal please check the following script: `./src/utils/export_for_unreal.py`

**Comment by yang1hu** [comment]
> Hi @yang1hu ! Thanks for your feedback. For export into Unreal please check the following script: `./src/utils/export_for_unreal.py`

thanks for your prompt responses and helpful guidance！I have successfully get the right result
