### ISSUE TITLE
Pytorch version mismatch between HAAR and k-diffusion

### ISSUE THREAD

**Issue by umariqbal-nvidia** [Vanessik/HAAR#2]
Hi Vanessa,

Great work! I am trying to run the code but keep getting `ModuleNotFoundError: No module named  'torch._dynamo'`. I suspect it is due to pytorch version mismatch between HAAR and k-diffusion. HAAR seems to use pytorch-1.13 where as k-diffusion requires pytorch>2.0. 

Any idea? 

Kind regards,
Umar

**Comment by yang1hu** [comment]
> Hi Vanessa,
> 
> Great work! I am trying to run the code but keep getting `ModuleNotFoundError: No module named 'torch._dynamo'`. I suspect it is due to pytorch version mismatch between HAAR and k-diffusion. HAAR seems to use pytorch-1.13 where as k-diffusion requires pytorch>2.0.
> 
> Any idea?
> 
> Kind regards, Umar

you can use other k-diffusion tags,which can math the project

**Comment by umariqbal-nvidia** [comment]
Yes, switching to commit `8fa87fd` for k-diffusion solved the problem.
