### ISSUE TITLE
image2hairstyle failed to get right results

### ISSUE THREAD

**Issue by yang1hu** [Vanessik/HAAR#3]
hello！when i try the  image2hairstyle to get the results. i found the results is alwawys the same no matter what picture i change.when i debug ,i found the discription of the image is the following:
![17182484938971](https://github.com/Vanessik/HAAR/assets/45646135/df850a30-5635-45b2-9353-de95093c393a)
I think [LLaVA](https://github.com/haotian-liu/LLaVA) return the bad results

**Comment by iiijasdf** [comment]
![image](https://github.com/user-attachments/assets/1250ec39-e959-4707-9a9f-c111c4f40220)
I might have a different problem when using image2hairstyle. I'm using example1.png as input but it seems like dimension mismatching.

**Comment by c-he** [comment]
image2hairstyle seems to work on my side. Though the results are reasonable, their quality is kind of poor.
<img width="1035" alt="Screenshot 2024-09-18 at 18 09 41" src="https://github.com/user-attachments/assets/c83571d0-b568-406c-bc2a-75dc416749a7">

**Comment by Vanessik** [comment]
@c-he Yes, the current approach is solely text-based and generation is not conditioned on any image features, that's why the quality is like that. An additional stage with personalized fine-tuning or conditioning diffusion model on image features may improve results.
