### ISSUE TITLE
Running “imagic_interpolation” failed

### ISSUE THREAD

**Issue by XiaokunSun** [Vanessik/HAAR#7]
Hello!
I followed your readme.md to run `python ./applications/imagic_interpolation.py  --conf ./configs/infer.json --hairstyle_edit_prompt 'short hairstyle' --target_hairstyle_texture 'exp_texture.pt' --save_guiding_strands --save_upsampled_hairstyle --save_latent_textures --upsample_resolution 128 --cfg_scale 1.5 --seed 32 --n_interpolation_states 5` but got the following error result, where is the 'exp_texture.pt' ?

**Comment by Vanessik** [comment]
Hi @XiaokunSun! Imagic_interpolation.py works as a modifier of some of the generated hairstyles (exp_texture.pt) with your text description. 

To check how it works the simplest way is first to run infer.py to generate this texture (see infer.py#L94) and then use it as exp_texture.pt.

**Comment by XiaokunSun** [comment]
I see! Thank you for your reply. By the way, I like your NeuralHaircut and HAAR, very nice works!
