### ISSUE TITLE
 the scalp UV coordinates in neuralhaircut and HAAR are different

### ISSUE THREAD

**Issue by XiaokunSun** [Vanessik/HAAR#8]
I noticed that the scalp UV coordinates in neuralhaircut and HAAR are different. Does this mean that the feature maps generated by the scalp neural texture diffusion models in the two works are not universal? In addition, why doesn't HAAR continue to use the scalp UV coordinates in neuralhaircut?

**Comment by Vanessik** [comment]
@XiaokunSun Nice catch, after some experiments, I understand that in the previous UV map, there were some inconsistencies in the basis vectors (maybe it appeared because of manual editing of uv map), so i generated a new one in Blender without any editing and its basis vectors looked better

**Comment by XiaokunSun** [comment]
I see, thank you!
